base_url = "https://rodolfoviana.com.br"
title = "rodolfo viana"
description = "aulas, estudos e publicações sobre ciência de dados"
default_language = "pt"
build_search_index = false
generate_feeds = false
compile_sass = true
minify_html = true
ignored_content = ["rascunhos/"]
taxonomies = [{ name = "tags" }]
author = "rodolfo viana"

# Multilingual configuration
[languages.en]
title = "rodolfo viana"
description = "classes, studies and publications about data science"
generate_feeds = false
taxonomies = [{ name = "tags" }]

[markdown]
highlight_code = true
highlight_theme = "monokai"
external_links_target_blank = true
smart_punctuation = false
bottom_footnotes = true
# extra_syntaxes_and_themes = ["syntaxes"]

[extra]
toc = true
use_cdn = false
favicon = "/favicon.png"
theme = "dark"
fancy_code = true
dynamic_note = true
comment = false
mathjax = true

# Default menu (Portuguese)
menu = [
    { name = "projetos", url = "projetos", weight = 2 },
    { name = "cv", url = "curriculo", weight = 3 },
    { name = "tags", url = "tags", weight = 4 }
]

custom_css = []
